server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: first-micro-service
          uri: http://localhost:8081
          predicates:
            - Path=/first-micro-service/**
          filters:
            - CustomFilter
        - id: second-micro-service
          uri: http://localhost:8082
          predicates:
            - Path=/second-micro-service/**
          filters:
            - CustomFilter

management:
  endpoints:
    web:
      exposure:
        include:
          - "gateway"
  endpoint:
    gateway:
      enabled: true